# Generated by Django 4.1.7 on 2023-07-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountedd_price',
            new_name='discounted_price',
        ),
    ]
