# Generated by Django 4.1.7 on 2023-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptop'), ('CR', 'Curd'), ('ML', 'MILK'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('SH', 'Shoes'), ('WA', 'Watch'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
