# Generated by Django 4.2.6 on 2024-01-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptop'), ('CR', 'Curd'), ('ML', 'MILK'), ('ST', 'Shirt'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('SH', 'Shoes'), ('WA', 'Watch'), ('BA', 'BAG'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
